language: c

env:
  - LUA="LuaJIT 2.0"

before_install:
  - bash .travis_setup.sh

install:
  - sudo luarocks make
  - sudo apt-get update -qq
  - sudo apt-get install -qq libev-dev
  - sudo luarocks install lua-ev scm --server=http://luarocks.org/repositories/rocks-scm/
  - sudo luarocks install copas
  - sudo luarocks install moonscript
  - sudo luarocks install lapis
  - sudo luarocks install penlight

script: make test

#branches:
#  except:
#    - gh-pages
