language: c
env:
  global:
    - PGSQL_USER=postgres
    - PGSQL_PASSWORD=
    - PGSQL_DATABASE=foosboy_adv
addons:
  postgresql: "9.3"
branches:
  only:
    - master
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libev-dev luarocks
  - sudo apt-get remove nginx
install:
  - bash .travis_setup.sh
  - sudo luarocks install luasec OPENSSL_LIBDIR=/usr/lib/x86_64-linux-gnu
  - sudo luarocks install lua-ev scm --server=http://luarocks.org/repositories/rocks-scm/
  - sudo luarocks install copas
  - sudo luarocks install lapis
  - sudo luarocks install penlight
  - sudo luarocks install busted 1.11.0
before_script:
  - psql -c 'create database foosboy_adv;' -U postgres
script:
  - make
  - lapis build travis
  - lapis exec 'require"lapis.db".query"select 1;"'
  - lapis exec 'require"schema".create_schema()'
  - lapis migrate
  - busted
