language: c
before_install:
- bash .travis_setup.sh
install:
- sudo apt-get update -qq
- sudo apt-get install -qq libev-dev luarocks
- sudo luarocks install lua-ev scm --server=http://luarocks.org/repositories/rocks-scm/
- sudo luarocks install copas
- sudo luarocks install moonscript
- sudo luarocks install lapis
- sudo luarocks install penlight
script: make test
deploy:
  provider: heroku
  api_key:
    secure: T8pkBAubI2cse39qiXU7r7Kao7LRC/L0x9lLmrQx0Na07G1q3Zb2CdY2GzIBIhooNnq81TUWv6EqrNmZgo4Nu4pvWRwmIgl4Q/YKIlOzF9YoU7EHM1Tz4HL9zsXpb9fT31UGLAnTOselr9QtKpg8DWLK/LIEBqO+CwtwAz0T+gI=
  app: foosboy-advanced
  on:
    repo: cahna/foosboy-advanced
