language: c
env:
  PGSQL_USER: "postgres"
  PGSQL_PASSWORD: ""
  PGSQL_DATABASE: "foosboy_adv"
addons:
  postgresql: "9.3"
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq libev-dev luarocks
- bash .travis_setup.sh
install:
- sudo luarocks install lua-ev scm --server=http://luarocks.org/repositories/rocks-scm/
- sudo luarocks install copas
- sudo luarocks install lapis
- sudo luarocks install penlight
- sudo luarocks install busted
before_script:
  - psql -c 'create database foosboy_adv;' -U postgres
script: make ci
deploy:
  provider: heroku
  api_key:
    secure: T8pkBAubI2cse39qiXU7r7Kao7LRC/L0x9lLmrQx0Na07G1q3Zb2CdY2GzIBIhooNnq81TUWv6EqrNmZgo4Nu4pvWRwmIgl4Q/YKIlOzF9YoU7EHM1Tz4HL9zsXpb9fT31UGLAnTOselr9QtKpg8DWLK/LIEBqO+CwtwAz0T+gI=
  app: foosboy-advanced
  on:
    repo: cahna/foosboy-advanced
